name-template: 'v$NEXT_MINOR_VERSION'
tag-template: '$NEXT_MINOR_VERSION'
categories:
  - title: 'New Features'
    label: 'feature'
  - title: 'Improvements'
    label: 'improvement'
  - title: 'Bug Fixes'
    label: 'bug'

change-template: '- $TITLE (@$AUTHOR - #$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
include-labels:
  - 'feature'
  - 'improvement'
  - 'bug'
template: |
  This release requires SkyHanni version 0.27.Beta.12

  $CHANGES
